language: erlang
otp_release:
  - 21.2.5
  - 20.3
  - 19.3
install:
  - make
  - ./rebar3 update
script:
  - make test
  - make xref
  - make dialyzer
  - make lint
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
sudo: false
